// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ticketflow/core/enums/ticket_category.dart';
import 'package:ticketflow/core/enums/ticket_priority.dart';
import 'package:ticketflow/core/enums/ticket_status.dart';
import 'package:ticketflow/features/tickets/data/models/ticket_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TicketCategoryAdapter());
    registerAdapter(TicketModelAdapter());
    registerAdapter(TicketPriorityAdapter());
    registerAdapter(TicketStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TicketCategoryAdapter());
    registerAdapter(TicketModelAdapter());
    registerAdapter(TicketPriorityAdapter());
    registerAdapter(TicketStatusAdapter());
  }
}
